openapi: 3.0.0
info:
  version: 1.0.0
  title: ratelimit-test
  x-ibm-name: ratelimit-test
servers:
  - url: /ratelimit-test
x-ibm-configuration:
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - switch:
          version: 2.1.0
          title: switch
          case:
            - condition: $queryParameter('user') = 'test'
              execute:
                - ratelimit:
                    version: 2.4.0
                    title: ratelimit
                    source: plan-named
                    rate-limit:
                      - name: ratelimit-test
                        operation: consume
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: console.log('****custom-rate-limit-executed****');
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: >-
            let vOutput = {};

            vOutput.ResponseDetails = {"APIName":""};

            vOutput.ResponseDetails.APIName = context.get('api.name');

            vOutput.ResponseDetails.GatewayIP =
            context.get('session.localAddress');

            vOutput.ResponseDetails.RequestDate = context.get('request.date');

            vOutput.ResponseDetails.ClientAddress =
            context.get('session.clientAddress');

            vOutput.ResponseDetails.TransactionID =
            context.get('session.transactionID');

            vOutput.ResponseDetails.GlobalTransactionID =
            context.get('session.globalTransactionID');


            context.message.body.write(vOutput);

            context.message.header.set('Content-Type', "application/json");

            context.message.statusCode = '200 YAY'
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    put:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    post:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    delete:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    head:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    patch:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    parameters:
      - name: clientid
        in: query
        required: true
        schema:
          title: clientid
          type: string
      - name: user
        in: query
        schema:
          title: user
          type: string
components:
  securitySchemes:
    clientid:
      type: apiKey
      x-key-type: client_id
      name: clientid
      in: query
security:
  - clientid: []
